pipeline {
    agent any
    stages {
        stage('打包入库') {
            steps {
		        sh 'mvn clean && mvn install'
            }
        }
        stage('清理代码') {
                steps {
                    sh 'rm -rf * &&  rm -rf .git*'
                }
            }
        }
}
