pipeline {
    agent any
    stages {
        stage('打包入库') {
            steps {
                //
		        sh 'mvn install'
            }
        }
        stage('清理环境') {
                steps {
                    //
                    sh 'rm -rf * && rm -rf .*'
                }
            }
        }
}
